baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"

[Params]
  [[Params.social]]
    name = "Twitter"
    url = "https://twitter.com/username"
  [[Params.social]]
    name = "GitHub"
    url = "https://github.com/username"
